# Generated by Django 2.2.9 on 2020-02-18 20:37

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('main', '0002_auto_20200218_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
