# Generated by Django 2.2.9 on 2020-02-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200218_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BigIntegerField(max_length=32),
        ),
    ]
