# Generated by Django 2.2.9 on 2020-02-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200220_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_file',
            name='path',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='audio_file',
            name='vocals_path',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BigIntegerField(),
        ),
    ]
